### PR TITLE
refactored download to use progress bar instead of status bar

### PR DESCRIPTION
**Pull request by lhein**
Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>

### CODE REVIEW

**Comment by bfitzpat** [comment]
This does not work here. The file is somehow not available when we do the chmod, so I get this stuff

```
Downloading Apache Camel K CLI to /home/bfitzpat/.config/Code/User/globalStorage/redhat.vscode-camelk/camelk/tools/kamel
installer.js:176
Downloaded /home/bfitzpat/.config/Code/User/globalStorage/redhat.vscode-camelk/camelk/tools/kamel/kamel successfully: false
installer.js:185
Downloading Kubernetes CLI to /home/bfitzpat/.vs-kubernetes/tools/kubectl
installer.js:257
Downloaded /home/bfitzpat/.vs-kubernetes/tools/kubectl/kubectl successfully: false
installer.js:264
Activating extension `redhat.vscode-camelk` failed:  ENOENT: no such file or directory, chmod '/home/bfitzpat/.vs-kubernetes/tools/kubectl/kubectl'
extensionHostProcess.js:496
Here is the error stack:  Error: ENOENT: no such file or directory, chmod '/home/bfitzpat/.vs-kubernetes/tools/kubectl/kubectl'
	at Object.chmodSync (fs.js:1001:3)
	at /home/bfitzpat/github/vscode-camelk/out/src/installer.js:271:16
	at Generator.next (<anonymous>)
	at fulfilled (/home/bfitzpat/github/vscode-camelk/out/src/installer.js:21:58)
```

I was not able to track down the problem yesterday, but this is the same reason I switched it to a simpler status bar update method.

**Comment by bfitzpat** [comment]
It definitely DOES download the files, but somehow there's an order of events issue where the chmodSync call simply doesn't find the file available.

**Comment by lhein** [comment]
I tracked that issue down. The download was basically still running when it signaled its done and then chmod failed because the file was still busy being downloaded. There is simply too much use of async / await in this extension. I only fixed the parts required to make the download functionality work. Please test and let me know if you have any problems.

**Comment by bfitzpat** [comment]
Closing this one for now. We can investigate again later.

**Pull request closed without merging**
